name: Create new release
on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Major, minor, patch?'
        options: 
        - ''
        - major
        - minor
        - patch
        required: false
        type: choice

      custom_release_name:
        description: 'Custom release name'
        default: '0.0.0'
        required: false
        type: string

jobs:
  lint_test_build:
    name: Lint, test and build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Lint, test and build"

  calculate_next_version:
    name: Calculate next version
    runs-on: ubuntu-latest
    outputs:
      next_version: ${{ steps.bump_version.outputs.NEXT_VERSION }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      if: "${{ github.event.inputs.bump_type != '' }}"
      with:
        fetch-depth: 0
        
    - name: Get latest tag
      if: "${{ github.event.inputs.bump_type != '' }}"
      run: | 
        LATEST_TAG=$(git describe --tags --match "v*" --abbrev=0 2>/dev/null || echo "v0.0.0")
        echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

    - name: Remove v prefix
      if: "${{ github.event.inputs.bump_type != '' }}"
      run: |    
        LATEST_VERSION=$(echo "$LATEST_TAG" | sed 's/v//')
        echo "LATEST_VERSION=$LATEST_VERSION" >>  $GITHUB_ENV

    - name: Bump version
      if: "${{ github.event.inputs.bump_type != '' }}"
      id: bump_version
      run: |
        MAJOR=$(echo "$LATEST_VERSION" | cut -d. -f1)
        MINOR=$(echo "$LATEST_VERSION" | cut -d. -f2)
        PATCH=$(echo "$LATEST_VERSION" | cut -d. -f3)
        if [ "${{ inputs.bump_type }}" == "major" ]; then
          MAJOR=$((MAJOR+1))
          MINOR=0
          PATCH=0
        elif [ "${{ inputs.bump_type }}" == "minor" ]; then 
          MINOR=$((MINOR+1))
          PATCH=0
        elif [ "${{ inputs.bump_type }}" == "patch" ]; then
          PATCH=$((PATCH+1))
        fi
        echo "NEXT_VERSION=$MAJOR.$MINOR.$PATCH" >> $GITHUB_OUTPUT

    - name: Manually set release name
      if: "${{ github.event.inputs.custom_release_name != '' }}"
      run: echo "NEXT_VERSION=${{ github.event.inputs.custom_release_name }}" >> $GITHUB_OUTPUT
        
  update_csproj:
      name: Update .csproj
      runs-on: ubuntu-latest
      needs: [lint_test_build, calculate_next_version]
      permissions:
        contents: write
      steps:
          - name: Checkout
            uses: actions/checkout@v4
  
          - name: Update .csproj file
            id: update
            uses: vers-one/dotnet-project-version-updater@v1.7
            with:
              file: "Example.csproj"
              version: ${{ needs.calculate_next_version.outputs.next_version }}

          - run: |
              git config user.name "${{ github.actor }}"
              git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
              git add .
              git commit -m "Update project version to ${{ needs.calculate_next_version.outputs.next_version }}"
              git push

  create_tag_and_release:
      name: Create tag and release
      runs-on: ubuntu-latest
      needs: [lint_test_build, calculate_next_version, update_csproj]
      permissions:
        contents: write
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Create release        
          run: gh release create "v${{ needs.calculate_next_version.outputs.next_version }}" --generate-notes
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy
    needs: [create_tag_and_release]
    permissions:
      contents: write
    uses: ./.github/workflows/deploy.yml
