name: Deploy
on:
  workflow_call:
jobs:
  deploy:
    name: Deploy to production server
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      SECRET_CONN_STRING: ${{ secrets.SECRET_CONN_STRING }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Hello
        run: echo "`jq --arg SECRET_CONN_STRING "$SECRET_CONN_STRING" '.connectionStrings.myConnectionString=$SECRET_CONN_STRING' appSettings.json`" > appSettings.json
      - name: read json
        run: cat appSettings.json

      - run: |
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
            git add .
            git commit -m "Update json"
            git push
