name: Deploy
on:
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy to production server
    runs-on: ubuntu-latest
    env:
      SECRET_CONN_STRING: ${{ secrets.SECRET_CONN_STRING }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Hello
        run: echo "`jq '.connectionStrings.myConnectionString="${{ SECRET_CONN_STRING }}"' appSettings.json`" > appSettings.json
      - name: read json
        run: cat appSettings.json
