name: Manual workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Major, minor, patch?'
        default: 'patch'
        required: true
        type: string
jobs:
  calculate:
    name: Calculate next version
    runs-on: ubuntu-latest
    steps:
    - run: | 
        LATEST_TAG=$(git describe --tags --match "v*" --abbrev=0 2>/dev/null || echo "v.0.0.0")
        echo "Latest tag: $LATEST_TAG"
        VERSION=$(echo "$LATEST_TAG" | sed 's/v//')
        echo "Version without v: $VERSION"
        SPLIT_VERSION='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
        echo "Split: $MAJOR, $MINOR, $PATCH"
