name: Manual workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Major, minor, patch?'
        default: 'patch'
        required: true
        type: string
jobs:
  calculate:
    name: Calculate next version
    runs-on: ubuntu-latest
    steps:
    - name: Get latest tag
    - run: | 
        LATEST_TAG=$(git describe --tags --match "v*" --abbrev=0 2>/dev/null || echo "v0.0.0")
        echo "Latest tag: $LATEST_TAG"

    - name: Remove v prefix
    - run: |    
        VERSION=$(echo "$LATEST_TAG" | sed 's/v//')
        echo "Version without v: $VERSION"

    - name: Bump version
    - run: |
        MAJOR=$(echo "$VERSION" | cut -d. -f1)
        MINOR=$(echo "$VERSION" | cut -d. -f2)
        PATCH=$(echo "$VERSION" | cut -d. -f3)
        if ["${{ github.event.inputs.name = 'major' }}"]; then $NEW_VERSION="((MAJOR+1)).0.0" 
        elif ["${{ github.event.inputs.name = 'minor' }}"]; then $NEW_VERSION="$MAJOR.((MINOR+1)).0"
        elif ["${{ github.event.inputs.name = 'patch' }}"]; then $NEW_VERSION="$MAJOR.$MINOR.((PATCH+1))"
        fi
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

    - name: Print new version
    - run: echo "$NEW_VERSION"  
