name: Manual workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Major, minor, patch?'
        default: 'patch'
        required: true
        type: string
jobs:
  calculate:
    name: Calculate next version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Get latest tag
      run: | 
        LATEST_TAG=$(git describe --tags --match "v*" --abbrev=0 2>/dev/null || echo "v0.0.0")
        echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

    - name: Remove v prefix
      run: |    
        VERSION=$(echo "$LATEST_TAG" | sed 's/v//')
        echo "VERSION=$VERSION" >>  $GITHUB_ENV

    - name: Bump version
      run: |
        MAJOR=$(echo "$VERSION" | cut -d. -f1)
        MINOR=$(echo "$VERSION" | cut -d. -f2)
        PATCH=$(echo "$VERSION" | cut -d. -f3)
        if [ ${{ github.event.inputs.name == 'major' }} ]; then
          MAJOR=$((MAJOR+1))
          MINOR=0
          PATCH=0
        elif [ ${{ github.event.inputs.name == 'minor' }} ]; then 
          MINOR=$((MINOR+1))
          PATCH=0
        elif [ ${{ github.event.inputs.name == 'patch' }} ]; then
          PATCH=$((PATCH+1))
        fi
        echo "NEW_VERSION=$MAJOR.$MINOR.$PATCH" >> $GITHUB_ENV

    - name: Print new version
      run: echo "$NEW_VERSION"  
